name        = "Erglace"
name8       = "erglace"
locale      = "fr"
variant     = "erglace"
description = "French (Erglace)"
author      = "Lysquid"
url         = "https://github.com/Lysquid/Erglace"
geometry    = "ERGO"
version     = "0.1.0"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ ~   ┃ !   │ @   │ #   │ $   │ %   ┃ ^   │ &   │ *   │ (   │ )   ┃ _   ┆ +   ┆
┆ `   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0   ┃ -   ┆ =   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Y   │**   │ O   │ F   │ K   ┃ B   │ P   │ L   │ C   │ W   ┃ {   ┆ }   ┆
·     ┃   ï │   ' │   ô │   è │   ù ┃     │     │     │   ç │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ I   │ A   │ E   │ U   │ ?   ┃ G   │ T   │ N   │ S   │ R   ┃ "   ┆ |   ┆
·     ┃   î │     │   ê │   é │ , û ┃   € │   â │   à │   æ │   œ ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ J   │ !   │ _   │ H   │ Z   ┃ Q   │ D   │ M   │ V   │ X   ┃           ·
┆ <   ┃   · │ . … │ - — │   ë │   ü ┃     │     │   µ │     │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃   % │   + │   [ │   ] │   # ┃   ^ │   : │   " │   ' │   $ ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   / ┃   = │   ← │   ↓ │   ↑ │   → ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃           ·
┆     ┃   ~ │   \ │   < │   > │   & ┃   | │   ; │   * │   ` │   @ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK